### ISSUE TITLE
How compile DLL with my code?

### ISSUE THREAD

**Issue by Troodi** [stephenfewer/ReflectiveDLLInjection#9]
If i write code where calling MessageBox - error compile. How i can instead MessageBox my code, example: load file using curl. Help please!

**Comment by Succubussix** [comment]
error compile? show us the error ...

**Comment by Troodi** [comment]
In ReflectiveDll.c wtite 
```
#include "ReflectiveLoader.h"
#include "iostream"
using namespace std;
```
Error: required ";" in using namespace std; How?
http://prntscr.com/ezh4o8 Screen.

**Comment by heklam** [comment]
Because you are compiling for the C Language and not C++
`ReflectiveDll.c` should be `ReflectiveDll.cpp`

iostream is a template libarly - it's not available in C
http://stackoverflow.com/questions/14746425/are-there-templates-in-the-c-programming-language

`using namespace std;`
http://stackoverflow.com/questions/4396140/why-doesnt-ansi-c-have-namespaces

Think you should learn the language first before attempting this form of module loading.

GitHub if not for Tutorials in Programming.

**Comment by Troodi** [comment]
Wow, I did not notice this. Thx!
